#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighlighterLib.Templating.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Directory.cshtml")]
    public partial class Directory : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Directory()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");


            
            #line 2 "..\..\Views\Directory.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral(@"
<!DOCTYPE html>

<html>
<head>
    <meta name=""viewport"" content=""width=device-width"" />
    <title>Directory</title>
</head>
<body>
    <div data-bind=""foreach: folder"">

    </div>
    <div data-bind=""foreach: file"">
        <div data-bind=""text: name"">
            <a data-bind=""attr: { href: url, title: details }"" href="""" target=""sourceexplorer""></a>
        </div>
    </div>
    <script type=""text/javascript"">
        var directoryStructure = ");


            
            #line 23 "..\..\Views\Directory.cshtml"
                            Write(Model.DirectoryJson);

            
            #line default
            #line hidden
WriteLiteral(";\r\n        var viewModel = new DIrectoryViewModel(directoryStructure);\r\n        k" +
"o.applyBindings(viewModel);\r\n    </script>\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
